### PR TITLE
WIP: Initial add of climate/spark benchmarks

### PR DESCRIPTION
**Pull request by notthatbreezy**
This is still kind of a WIP -- it compiles, but not sure this is the package naming scheme we want to use or what, so I'm putting this up there. I've used it to do some ingests of data from S3.

### CODE REVIEW

**Comment by lossyrob** [comment]
Nice. have you successfully run these against a cluster?

**Comment by lossyrob** [comment]
Naming scheme works for me.

**Comment by notthatbreezy** [comment]
Ok - after inspecting things a little more closely, I think there are a few things that need to be fixed...ingest seems not to be ingesting much data actually, it's pulling everything down, but for some reason it's not ending up in accumulo ugh.

**Comment by notthatbreezy** [comment]
I think this can be merged now -- the issue was that bug in the geotrellis ingest code (https://github.com/geotrellis/geotrellis/pull/1067)

**Pull request merged**
